# Generated by Django 4.1.2 on 2022-11-10 17:33

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_age_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[users.validators.check_age_user], verbose_name='День рождения'),
        ),
    ]
