# Generated by Django 4.1.2 on 2022-11-10 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_images_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
